spring.application.name=insurance-notification-service
server.port = 8110

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Kafka Consumer Configuration (Listening for Events)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# 2. Key Configuration (Standard)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 3. CRITICAL: Ignore the "Type Header" sent by the Producer
# This tells the consumer: "I don't care what Java class you were. Convert the JSON to *my* class."
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 4. Explicitly tell it which class to map the JSON to
spring.kafka.consumer.properties.spring.json.value.default.type=com.insurance_notification.dto.NotificationEvent

# 5. TRUST ALL (Keep this just in case)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tanmaydhelia.labs@gmail.com
spring.mail.password=hfuxqxhjbipmqcyz
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000