spring.application.name=insurance-config-server
server.port=8888

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

##Config Server : Local
spring.cloud.config.server.native.search-locations=classpath:/config

## Config Server - Git Repo
#spring.cloud.config.server.git.uri=https://github.com/tanmaydhelia/insurance-config-repo
#spring.cloud.config.server.git.clone-on-start=true
#spring.cloud.config.server.git.default-label=main

# Enable native profile
spring.profiles.active=native

# Actuator
management.endpoints.web.exposure.include=*